### ISSUE TITLE
[Bug] 2倍缩放时坐下位置悬浮

### ISSUE THREAD

**Issue by KJH-x** [isHarryh/Ark-Pets#10]
2.0倍率缩放走动站立都是正常的，坐下会浮空，如图所示
 - 以白面为例
<img width="163" alt="截图_20221018235425" src="https://user-images.githubusercontent.com/53437291/196481395-6e8f0d5e-c252-418d-b94f-c40a11dbe34e.png">

 - 以鸿雪为例
<img width="158" alt="截图_20221018235449" src="https://user-images.githubusercontent.com/53437291/196481502-eeaa858b-bdb7-4c9b-a078-691a6d7440a9.png">

（其他设置保持默认）

**Comment by isHarryh** [comment]
已于 https://github.com/isHarryh/Ark-Pets/commit/aeed29a9bf25db445ef15801a83172e1b84d1ccd 修复此问题。
