### ISSUE TITLE
[Enhancement] 窗体速度及边缘反弹建议

### ISSUE THREAD

**Issue by KJH-x** [isHarryh/Ark-Pets#11]
观察到目前丢到左右边缘时逻辑是
 - ν<sub>x1</sub> = 0
 - ν<sub>y1</sub> = ν<sub>y0</sub>

~~同时对于脱手速度貌似没有检测~~
<br>
建议改为
 - ν<sub>x1</sub> = - ν<sub>x0</sub>
 - ν<sub>y1</sub> = ν<sub>y0</sub>

~~并加入速度探测 可增加可玩性~~

**Comment by isHarryh** [comment]
关于第一个提议，让小人碰到左右边缘后反弹，这是一个很好的想法。

**Comment by isHarryh** [comment]
关于第二个提议，脱手速度其实是会检测的，只是限制了最大瞬时移速导致你感觉得不明显。参见：
https://github.com/isHarryh/Ark-Pets/blob/d35fadf08ad77c3e3c4799ecc3da44444d3c7b5a/core/src/com/isharryh/arkpets/ArkPets.java#L75
可以看到，目前设置的移速限制是：
> X方向：屏幕宽度(px)*0.25/s  
> Y方向：屏幕高度(px)*0.75/s

**Comment by isHarryh** [comment]
https://github.com/isHarryh/Ark-Pets/commit/d31f49bf116b836bac6b9d1a2db83f72c216e31a 已经为重力场添加了反弹系数的设置接口：
https://github.com/isHarryh/Ark-Pets/blob/d31f49bf116b836bac6b9d1a2db83f72c216e31a/core/src/com/isharryh/arkpets/utils/Plane.java#L55-L60
但考虑到反弹的观感有些怪异，所以目前不设置反弹系数。

**Comment by isHarryh** [comment]
另外，为了更好的拖拽体验，已将速度限制调高了，现在设置的是：
https://github.com/isHarryh/Ark-Pets/blob/d31f49bf116b836bac6b9d1a2db83f72c216e31a/core/src/com/isharryh/arkpets/ArkPets.java#L77
