### ISSUE TITLE
[Enhancement] 启动方式相关建议

### ISSUE THREAD

**Issue by KJH-x** [isHarryh/Ark-Pets#12]
## 启动方式建议
- [x] 单个启动->批量启动（也许可以再套多一层壳？比如一个批量能批量启动启动器的启动器）
- [x] 添加命令行启动方法，传入各项参数：
  - ~~各项设置~~ `(Not Planned - 作者注)`
  - 是否显示启动器窗体
- [x] ~~可编辑的配置文件（设置启动个数，各个实例的各项参数），存在配置文件的时候自动按配置文件启动~~ `(Not Planned - 作者注)`

**Comment by isHarryh** [comment]
关于批量启动的建议， ~~本项目在短期内不计划支持~~ 。

关于命令行启动，短期内会提供`直接启动桌宠不显示选择窗体`的选项。

关于配置文件，目前（v2.x版本）在工作目录下由`ArkPetsConfig.json`文件以json的形式存储单个桌宠的启动选项。

**Comment by isHarryh** [comment]
批量启动已于  b6ef359dcae258cea9fab2fd9bac3fd199bc3ef6 实现。现在启动器不会在启动单个桌宠后立即关闭，可以多次启动桌宠。

**Comment by isHarryh** [comment]
本议题全部内容已处理完成，现在关闭此议题，感谢支持。
