### ISSUE TITLE
[Bug] 模型边框裁剪问题

### ISSUE THREAD

**Issue by KaiserWilheim** [isHarryh/Ark-Pets#14]
主要出现在部分卡特斯干员身上（因为耳朵实在是太长了）

放三张图：
![image.png](https://s2.loli.net/2022/10/30/KajyQ3dMSZJAPg7.png)
![image.png](https://s2.loli.net/2022/10/30/ziq4pUYfhot3eSR.png)
![image.png](https://s2.loli.net/2022/10/30/CY5uFnDePjpcf86.png)

主要就是耳朵会直接溢出边框，顶面侧面都有。

**Comment by isHarryh** [comment]
此议题为重复议题，将直接关闭。
