### ISSUE TITLE
[Bug] 小人在窗口上缘与屏幕上缘距离小于应用高度时显示异常

### ISSUE THREAD

**Issue by KaiserWilheim** [isHarryh/Ark-Pets#15]
如题。
给个图：
![QQ录屏20221030195109.gif](https://s2.loli.net/2022/10/30/tH2ngiINRVO6Zyh.gif)

这种情况会出现在屏幕上边框 - 窗口上边框 < 小人高度的情况下出现。
给个图：
![2022-10-30 20-03-03.gif](https://s2.loli.net/2022/10/30/6dTji5PYh2GEtC1.gif)

（这回应该不会再重了罢）

**Comment by isHarryh** [comment]
此问题经测试确实发生于`v1.4.0`版本，将会在后续修复。

**Comment by isHarryh** [comment]
已于 https://github.com/isHarryh/Ark-Pets/commit/afa7bb94cd46c1d51725f4bb58b7ac462d729bdc 修复此问题。

**Comment by KaiserWilheim** [comment]
改了之后感觉对边界的识别模糊了很多……
![](https://s2.loli.net/2022/11/07/Y4RCTWJFV9QtMlm.gif)
我是不是需要开一个新issue？

**Comment by isHarryh** [comment]
出现此种情况的原因可能是：
- 该窗口具有阴影或其他不可见外部实体，导致其上边距高度增加。
- 该位置存在多个窗口，或者有其他不可见窗口。

若您确定该问题不是由于上述原因导致，且此问题可以通过具体步骤复现，则可以提交新Issue。
