### ISSUE TITLE
[Bug] 模型位置计算

### ISSUE THREAD

**Issue by undefined-moe** [isHarryh/Ark-Pets#16]
复现方式：

版本 v1.5.0

1. 载入 `358_lisa_lzh#1` , 不允许坐下，缩放比 2.0，底部边界 0
2. 将 Windows 任务栏移动到左侧。
3. 将模型拖拽至屏幕左下角任务栏旁。
4. 打开 PC QQ。
5. 选中 ArkPets 窗口至最前端。（概率复现，可尝试最小化后再点开）
6. 等待新消息，鼠标悬停任务栏闪烁头像
7. 模型会被弹框顶上去

![image](https://user-images.githubusercontent.com/29992205/200149107-2f40177d-ca76-4f94-8ede-fbe81203b67f.png)

**Comment by isHarryh** [comment]
**该现象已知悉，属于正常特性。**
任务栏弹出窗口我们按照一般窗口对待，所以小人支持站立在弹出窗口上，若该弹出窗口上边缘高度小于桌宠窗口高度，则会被弹到目标窗口上方。
