### ISSUE TITLE
[Bug] 窗体边缘识别模糊

### ISSUE THREAD

**Issue by KaiserWilheim** [isHarryh/Ark-Pets#17]
窗体边缘识别模糊

软件设置：因为任务栏高度是40所以将下边缘距离设为40，其他默认
操作：

实验1：
1. 打开软件，选择任意一款模型，等待其从默认位置落下
2. 落下之后角色距任务栏仍有约30
3. 将角色拖到较低的位置（距任务栏约300）并使其自由落下
4. 落下之后角色距任务栏仍有约10
5. 将角色拖到较高的位置（距任务栏约900）并使其自由落下
6. 落下之后角色距任务栏仍有约30
7. 等待角色坐下并点击其使其站起
8. 站起之后角色正好在任务栏上方
9. 等待角色坐下并点击其使其站起
10. 站起之后角色陷入任务栏约5

实验2：
1. 打开软件，选择任意一款模型，等待其从默认位置落下
2. 打开一个 Google Chrome 浏览器的新标签页
3. 将 Chrome 的窗口大小调整至约600，并将其拖动至下缘距任务栏约100
4. 将角色拖动至 Chrome 窗口上方稍高位置并使其自由落下
5. 落下之后角色距窗口上缘仍有约10
6. 重复4
7. 落下之后角色正好在窗口上缘位置
8. 不断重复操作4
9. 5和7的情况等概率出现
10. 将角色拖动至标签页内部并使其自由落下
11. 角色直接略过标签页下缘，落下之后角色距任务栏仍有约30
12. 将标签页托从至下缘距任务栏约300，并重复操作10
13. 角色直接略过标签页下缘，落下之后角色距任务栏仍有约30

系统是Win10，软件版本是v1.15.0
如果需要视频的话我可以发QQ（

**Comment by isHarryh** [comment]
已收到反馈，我们会在后续进行排查。感谢您的支持。

**Comment by KJH-x** [comment]
## 相似的问题：
<img width="351" alt="截图_20221113105237" src="https://user-images.githubusercontent.com/53437291/201503361-35e00554-d0bc-402d-9af0-e8a0f00f746d.png">

<ul>
<li>任务栏高度60px（默认），红框高度测量为230px，大部分时间都在这个高度虚空漫步</li>
<li>在Alt + Tab期间会下落，长按情况下，最终落回任务栏高度</li>
<li>启动时位置正常(+60px)，拖动之后开始出现如上异常</li>
</ul>

<table>
<tr>
<td>
<img height="50%" alt="截图_20221113110234" src="https://user-images.githubusercontent.com/53437291/201503612-42afad84-1914-4476-b79c-11deeeddc761.png"></td><td>
<img height="50%" alt="截图_20221113110945" src="https://user-images.githubusercontent.com/53437291/201503784-54bb48d0-7227-406d-b5fb-15306d2d4a38.png"></td>
</tr></table>

<ul>
<li>此时测量高度为弹出窗口(+80px)，位于（0+60+220+80=360px）的位置</li>
<li>无论x坐标，都会受到影响（即：即使人物不在弹出窗口正上方）</li>
</ul>

<h2>别的建议</h2>
<ul>
<li>增加窗口下边缘的贴靠，感觉会比上边缘更实用（？）</li>
</ul>

**Comment by isHarryh** [comment]
该问题是由于Windows任务栏预览窗口具有透明窗口实体，相似问题还包括联想电脑管家加速球。鉴于此类问题较为复杂，修复可能推迟或不修复。
对于增加下边缘贴靠的建议，我觉得可以采纳。

**Comment by isHarryh** [comment]
@KaiserWilheim ，我已上传新的[Release](https://github.com/isHarryh/Ark-Pets/releases/tag/v1.5.1)`v1.5.1-b1`，我这边测试证明Bug已无法复现，请你测试一下是否解决。

**Comment by isHarryh** [comment]
> @KaiserWilheim ，我已上传新的[Release](https://github.com/isHarryh/Ark-Pets/releases/tag/v1.5.1)`v1.5.1-b1`，我这边测试证明Bug已无法复现，请你测试一下是否解决。

包括你提出的“Windows任务栏预览窗口”相关问题，我这边测试证明已得到缓解，请你也留意一下。

**Comment by KaiserWilheim** [comment]
@isHarryh 窗口上缘识别已经正常，但是下缘貌似仍然不能识别（
VS下缘识别正常，但是Chrome下缘识别不上

**Comment by isHarryh** [comment]
> @isHarryh 窗口上缘识别已经正常，但是下缘貌似仍然不能识别（
> VS下缘识别正常，但是Chrome下缘识别不上

虽然但是，下边缘识别功能还没加入哦。

**Comment by isHarryh** [comment]
> > @isHarryh 窗口上缘识别已经正常，但是下缘貌似仍然不能识别（
> > VS下缘识别正常，但是Chrome下缘识别不上
> 
> 虽然但是，下边缘识别功能还没加入哦。

下边缘将在后续作为optional的功能加入。

**Comment by KaiserWilheim** [comment]
> 虽然但是，下边缘识别功能还没加入哦。

草了，那VS是怎么被识别上的（

**Comment by KaiserWilheim** [comment]
所以说这玩意应该可以close了罢？

**Comment by isHarryh** [comment]
> 草了，那VS是怎么被识别上的（

好问题，可能是不可见窗口实体（汗），录个视频看看？

**Comment by isHarryh** [comment]
> 所以说这玩意应该可以close了罢？

不急，到时候我来关闭。

**Comment by KaiserWilheim** [comment]
> > 草了，那VS是怎么被识别上的（
> 
> 好问题，可能是不可见窗口实体（汗），录个视频看看？

您不如自己下一个试试（
比如说这样可以识别：
![image.png](https://s2.loli.net/2022/11/17/vuFiKXHC2pAkElW.png)
这种窗口甚至也可以识别：
![image.png](https://s2.loli.net/2022/11/17/BGFivnIa8fTy9kh.png)
所以闲着没事的时候就可以拿大量的后者玩小人（

**Comment by isHarryh** [comment]
Hhhhh... 大概率是VS的内窗口的直接父窗口是Desktop(桌面根窗口) 蛮有趣的

**Comment by KJH-x** [comment]
> Hhhhh... 大概率是VS的内窗口的直接父窗口是Desktop(桌面根窗口) 蛮有趣的

自上次更新上缘站立之后就一直可以识别这种悬停消息窗口[ToolTip](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.tooltip.settooltip?view=windowsdesktop-7.0)
<br>
目前发现常用类似的还有右键菜单等窗口化图层会被检测

**Comment by isHarryh** [comment]
关于窗体下边缘贴靠的建议，综合多方面因素考虑后认为实现的效果可能不好， **暂时搁置**。

本议题涉及的两个内容：
- @KaiserWilheim  ：窗体下边缘识别模糊
- @KJH-x  ：增加窗体下边缘贴靠

已经全部处理完成，现在议题将关闭。
