### ISSUE TITLE
[Bug] 小人有时候会陷入任务栏

### ISSUE THREAD

**Issue by Flamarine** [isHarryh/Ark-Pets#2]
![image](https://user-images.githubusercontent.com/62203463/193853998-a8d16470-2f01-4127-9fdc-026c11c988ed.png)

**Comment by isHarryh** [comment]
该问题我已知悉。初步判定是由于某些动作同时进行导致窗口Y坐标的偏移量，其定义参见：
https://github.com/isHarryh/Ark-Pets/blob/d35fadf08ad77c3e3c4799ecc3da44444d3c7b5a/core/src/com/isharryh/arkpets/ArkPets.java#L46
设置错误。将在后续版本中修复，感谢您的反馈，mua~

**Comment by isHarryh** [comment]
已于[`feaa6f`](https://github.com/isHarryh/Ark-Pets/commit/feaa6fa5ffad183d1bb14f6b8057a6c5e2ba31c6)修复此问题。
此问题是由于在更新行为时，Sit动作的窗口Y坐标偏移量覆盖了不可打断动作的偏移量。现在在该动作不可打断时，将不会更改此偏移量。
