### ISSUE TITLE
[Feature Request] 窗口全屏时小人隐藏建议

### ISSUE THREAD

**Issue by lightningrealm** [isHarryh/Ark-Pets#24]
ppt播放和进入游戏时小人仍然存在屏幕图层最上层，希望可以增添一个全屏时隐藏小人选项

**Comment by isHarryh** [comment]
考虑到部分壁纸软件（例如WallpaperEngine）、部分录屏软件等的窗口特征与PPT放映、全屏游戏的窗口特征一致，可能会导致误隐藏，此功能可行性有待继续研究。
