### ISSUE TITLE
[Bug] 关于归溟幽灵鲨-斗争血脉的裁切问题

### ISSUE THREAD

**Issue by Misaka2298** [isHarryh/Ark-Pets#25]
![image](https://user-images.githubusercontent.com/99007518/235621849-acc52a81-9f90-48b3-b195-2d8b7821e206.png)
不清楚是模型本来如此还是其他问题

**Comment by isHarryh** [comment]
此问题属于边界裁切问题，参见议题 [#4](https://github.com/isHarryh/Ark-Pets/issues/4)

裁切问题经过 #4 中所提及的优化后，已经得到缓解。但对此问题所做的干预越多，稳定性和用户体验可能越差，后续会继续进行酌情的优化。
