### ISSUE TITLE
[Bug] 打开控制中心后小人陷入任务栏

### ISSUE THREAD

**Issue by dnyyfb** [isHarryh/Ark-Pets#27]
版本`2.0.0`。  
Win11系统下，只要打开控制中心（后测试，打开开始菜单、搜索栏、任务视图均有此问题），所有位于任务栏上的小人便会掉落至任务栏后端（底端）；将焦点离开任务栏后恢复正常。见视频： https://user-images.githubusercontent.com/63101620/236262565-12ec725e-cd01-4bc7-a30a-3a7ba7998cbd.mp4

**Comment by dnyyfb** [comment]
使用版本`2.0.1`调整下边界至70后 ，掉落至底端现象基本消失；但仍然会失去前置，将焦点离开任务栏后恢复正常。
见视频： https://github.com/isHarryh/Ark-Pets/assets/63101620/83dc0618-4743-4a36-b92a-1b28f9e37e73

**Comment by isHarryh** [comment]
经研究，掉落至底部是由于：
- 未打开开始菜单时，任务栏的高度为 H，桌宠可以站立到 H 处；
- 打开开始菜单后，任务栏实体消失导致未检测到窗口，或者任务栏高度增大为 (H+h) 且 h 大于桌宠高度 导致未实现站立。

此类问题可以通过 **调整下边界距离** 解决。

而失去前置是因为，任务栏与桌宠都是置顶(TOPMOST)的窗口，点击任务栏后其层叠次序(z-index)被置于最先，属于正常现象。

**Comment by dnyyfb** [comment]
根据我的DPI缩放150%，将下边界距离调至72后，就完全不会有陷入任务栏现象了。~~除了全屏时有点怪就是啦~~
前置这个问题和陷入任务栏是有关系的，所以也一起解决了。
感谢您花了这么长时间研究这些问题。
