### ISSUE TITLE
[Feature Request] 添加按星级筛选等功能

### ISSUE THREAD

**Issue by WSMTBG** [isHarryh/Ark-Pets#28]
今天突发奇想的想放满小车结果只能一个个找
小人不会说话总感觉怪怪的
谢谢

**Comment by isHarryh** [comment]
建议已收到。

- [x] 加入按照干员稀有度筛选的功能
- [ ] 加入干员语音（可能会在 *很* 未来实现）

**Comment by half-nothing** [comment]
干员语音的话，比较麻烦
不是说代码上的麻烦，是很难对语音做整体性的管理
代码我已经基本实现了，[在这里](https://github.com/half-nothing/Ark-Pets)
如果乐意自己搞搞配置 ~~（但是又有几个人乐意这么搞呢）~~ 的话，还是可以用的

**Comment by isHarryh** [comment]
已于 ff82a1e21ce396c345038b4cb340f10eeca89cf2 添加按照 TAG 筛选角色的功能。在模型库更新相关的 TAG 后即可实现按照星级筛选。

本议题的主要诉求已实现。干员语音作为长期任务，将单独讨论。
