### ISSUE TITLE
[Bug] 泰拉大陆调查团边界裁切问题

### ISSUE THREAD

**Issue by WSMTBG** [isHarryh/Ark-Pets#29]
有人提过，但泰拉大陆调查团的小人跳起的时候会消失一块

**Comment by isHarryh** [comment]
所以你遇到的所谓“消失”现象还是属于通常意义的“裁切”问题吗？

**Comment by WSMTBG** [comment]
> 所以你遇到的所谓“消失”现象还是属于通常意义的“裁切”问题吗？

应该是裁切

**Comment by isHarryh** [comment]
该议题之前已被提出过，请不要提交相同议题，此议题将直接关闭。撰写议题标题和正文时，请使用书面化语言完整而准确地描述问题，并遵守[议题规范](https://github.com/isHarryh/Ark-Pets/blob/v2.x/docs/Issues.md#议题规范)。
