### ISSUE TITLE
[Bug] 发现几个小问题

### ISSUE THREAD

**Issue by undefined-moe** [isHarryh/Ark-Pets#3]
1. 有一种人，他们不喜欢把任务栏放在下面
2. 部分动画产生较突兀边界
3. 多个模型交叠时会闪烁
4. 任务栏常驻窗口希望可以隐藏

![image](https://user-images.githubusercontent.com/29992205/193893108-a7f317e2-872f-445d-aa48-88535da0ffbc.png)
![image](https://user-images.githubusercontent.com/29992205/193893172-bc5c9f2a-48d8-4d24-9b9a-e4cc589e6e4c.png)

**Comment by undefined-moe** [comment]
以及这个 Jaaaaavaaaaaaaa 是不是有点过于恐怖了（
![image](https://user-images.githubusercontent.com/29992205/193893508-c657387e-8bcc-4bd6-8c2a-2e449662de49.png)

**Comment by ChuJiani** [comment]
如果距离底部边界距离是写死的的话，建议加入手动调整的功能，当然这样会不可避免带来坐时腿部出界的情况

**Comment by undefined-moe** [comment]
目测是内存回收有问题 在 launcher 里面把各个模型都切换一遍内存占用就会越来越大）

**Comment by undefined-moe** [comment]
以及如果能一个实例同时处理多个模型的话似乎可以更省资源；
以及这个 Launcher 好像不尊重系统 UI 的缩放设置

**Comment by undefined-moe** [comment]
当把模型扔上去下落的途中如果刚好模型开始行走的话会中止下落过程，改为往斜下方匀速走路，观感挺怪异的）

**Comment by isHarryh** [comment]
> 目测是内存回收有问题 在 launcher 里面把各个模型都切换一遍内存占用就会越来越大）

调试时确有注意到内存占用呈不正常增长，但短时间内没有影响我就没注意（

**Comment by isHarryh** [comment]
> 当把模型扔上去下落的途中如果刚好模型开始行走的话会中止下落过程，改为往斜下方匀速走路，观感挺怪异的）

哈哈哈哈哈笑死我了

**Comment by isHarryh** [comment]
> 如果距离底部边界距离是写死的的话，建议加入手动调整的功能，当然这样会不可避免带来坐时腿部出界的情况

启动器可以调整下边界距离哦

**Comment by isHarryh** [comment]
总而言之非常感谢你的建议，在我能力范围内我会尝试解决的

**Comment by isHarryh** [comment]
> 以及这个 Jaaaaavaaaaaaaa 是不是有点过于恐怖了（ ![image](https://user-images.githubusercontent.com/29992205/193893508-c657387e-8bcc-4bd6-8c2a-2e449662de49.png)

经过测试，针对此疑似内存泄漏的问题无法复现，故认为此问题不存在。如您认为仍存在可继续评论。

**Comment by isHarryh** [comment]
该议题内的主要bug已于[`bcbe4c`](https://github.com/isHarryh/Ark-Pets/commit/bcbe4cbea63406ec15c74cd80e7dbaf7cf9ec0f0)修复，议题将被关闭。

**Comment by KJH-x** [comment]
emmm，交叠闪烁和空中漫步是还没修复莫，11天前close的但是6天前的release还是有这问题呀

**Comment by isHarryh** [comment]
> emmm，交叠闪烁和空中漫步是还没修复莫，11天前close的但是6天前的release还是有这问题呀

请再次确认您使用的版本是否是`v1.3`？

**Comment by KJH-x** [comment]
抱歉，我想起来了，1.3应该是没有我说的这两个问题的
但是1.3在我的电脑上无法正常运行超过一分钟，导致我一直在用1.2
具体表现为启动时就非常卡顿，大概30s后就未响应了，看进程分析是有问题的，我重新在另一个issue开吧

<img width="446" alt="截图_20221023124642" src="https://user-images.githubusercontent.com/53437291/197374341-9e7c6b1d-ebf7-43cb-8c1b-781d439fc691.png">

> Update:
> 已于 Issue #13 解决此问题 —— 作者注
