### ISSUE TITLE
[Exception] 启动器界面文本乱码

### ISSUE THREAD

**Issue by itscpj** [isHarryh/Ark-Pets#31]
版本`v2.0.1`，~~安装简体中文和English两种语言版本后~~ 使用exe安装后应用界面乱码。  
此为图片链接：https://imgse.com/i/p9cfVUg

![p9cfVUg.png](https://github.com/isHarryh/Ark-Pets/assets/107977864/186711f2-ce36-4c34-a840-1f1534d0e01d)

**Comment by isHarryh** [comment]
乱码问题罕见，之前遇到过一个用户也是乱码：

![-221e85888b04a436.jpg](https://github.com/isHarryh/Ark-Pets/assets/107977864/a7fbeb11-aa4f-418d-8929-969e2f07b3f1)

但他的乱码情况和你的不一样。

**Comment by isHarryh** [comment]
已发布临时测试版本`v2.1.0-beta`，通过显式指定 JavaFX 字体尝试解决乱码问题。请你下载并尝试是否解决。

**Comment by itscpj** [comment]
> 已发布临时测试版本`v2.1.0-beta`，通过显式指定 JavaFX 字体尝试解决乱码问题。请你下载并尝试是否解决。

没有，还是和之前一样

**Comment by Aloento** [comment]
你把这个页面截个图
![image](https://github.com/isHarryh/Ark-Pets/assets/11802769/5452009a-8b24-4e0d-9d4d-5f9bc8be8d0a)


另见：[进入 Region Settings 页面的方法](https://jingyan.baidu.com/article/948f59243b4608990ff5f9f0.html)

**Comment by itscpj** [comment]
https://imgse.com/i/p92Ylfe
我没勾选UTF-8，编码是GBK

![p92Ylfe.png](https://github.com/isHarryh/Ark-Pets/assets/107977864/7271a5c1-5d2d-401b-9063-74f0999364db)

**Comment by isHarryh** [comment]
> https://imgse.com/i/p92Ylfe
> 我没勾选UTF-8，编码是GBK
> 
> ![p92Ylfe.png](https://github.com/isHarryh/Ark-Pets/assets/107977864/7271a5c1-5d2d-401b-9063-74f0999364db)

你的区域设置是正确的。现在我已重新上传`v2.1.0-beta`的程序文件，请你重新安装后，将日志等级调为`DEBUG`，然后发出你的`desktop.log`日志，以检查 Java 编码问题。

**Comment by itscpj** [comment]
```
# *** ArkPets Log - desktop (PID37292) ***
# Created: 2023-05-17 22:15:09,340
# OS: Windows 11 (amd64)
# Java version: 17.0.7
# Working directory: D:\ArkPets

22:15:09,376 [INFO] Config: Default config was copied successfully.
22:15:09,516 [INFO] System: Entering the app of DesktopLauncher
22:15:10,837 [INFO] Launcher: Initializing (JavaFX 20-ea, ArkPets 2.1.0)
22:15:10,842 [INFO] Launcher: Initialized
22:15:11,807 [INFO] Network: Downloading https://arkpets.harryh.cn/p/arkpets/client/api.php?type=queryVersion&cliVer=2.1.0&source=auto to temp/ApiQueryVersionCache
22:15:12,169 [WARN] ModelManager: Failed to initialize model dataset due to file not found. (models_data.json (系统找不到指定的文件。))
22:15:12,174 [INFO] ModelManager: Search "" (0)
22:15:12,206 [INFO] ModelManager: Reloaded
22:15:13,475 [INFO] Network: Downloaded temp/ApiQueryVersionCache , file size: 181
22:15:13,476 [INFO] Checker: Application version check finished
```

**Comment by isHarryh** [comment]
> ```
> # *** ArkPets Log - desktop (PID37292) ***
> # Created: 2023-05-17 22:15:09,340
> # OS: Windows 11 (amd64)
> # Java version: 17.0.7
> # Working directory: D:\ArkPets
> 
> 22:15:09,376 [INFO] Config: Default config was copied successfully.
> 22:15:09,516 [INFO] System: Entering the app of DesktopLauncher
> 22:15:10,837 [INFO] Launcher: Initializing (JavaFX 20-ea, ArkPets 2.1.0)
> 22:15:10,842 [INFO] Launcher: Initialized
> 22:15:11,807 [INFO] Network: Downloading https://arkpets.harryh.cn/p/arkpets/client/api.php?type=queryVersion&cliVer=2.1.0&source=auto to temp/ApiQueryVersionCache
> 22:15:12,169 [WARN] ModelManager: Failed to initialize model dataset due to file not found. (models_data.json (系统找不到指定的文件。))
> 22:15:12,174 [INFO] ModelManager: Search "" (0)
> 22:15:12,206 [INFO] ModelManager: Reloaded
> 22:15:13,475 [INFO] Network: Downloaded temp/ApiQueryVersionCache , file size: 181
> 22:15:13,476 [INFO] Checker: Application version check finished
> ```

诶，我忘了你乱码没法在启动器调日志等级。  
请打开安装目录下的`ArkPetsConfig.json`，将字段`logging_level`从`INFO`改为大写`DEBUG`，保存后再启动启动器，然后再发送新的`desktop.log`日志。

**Comment by itscpj** [comment]
```
# *** ArkPets Log - desktop (PID30704) ***
# Created: 2023-05-18 19:24:20,962
# OS: Windows 11 (amd64)
# Java version: 17.0.7
# Working directory: D:\ArkPets

19:24:21,906 [INFO] System: Entering the app of DesktopLauncher
19:24:26,333 [INFO] Launcher: Initializing (JavaFX 20-ea, ArkPets 2.1.0)
19:24:26,334 [DEBUG] Launcher: Property file.encoding = GBK
19:24:26,334 [DEBUG] Launcher: Property sun.jnu.encoding = GBK
19:24:26,334 [DEBUG] Launcher: Default charset = GBK
19:24:26,378 [INFO] Launcher: Initialized
19:24:28,605 [INFO] Network: Downloading https://arkpets.harryh.cn/p/arkpets/client/api.php?type=queryVersion&cliVer=2.1.0&source=auto to temp/ApiQueryVersionCache
19:24:29,096 [WARN] ModelManager: Failed to initialize model dataset due to file not found. (models_data.json (系统找不到指定的文件。))
19:24:29,098 [INFO] ModelManager: Search "" (0)
19:24:29,128 [INFO] ModelManager: Reloaded
19:24:31,095 [INFO] Network: Downloaded temp/ApiQueryVersionCache , file size: 183
19:24:31,096 [INFO] Checker: Application version check finished
19:24:46,155 [INFO] System: Exited from DesktopLauncher successfully
```

**Comment by isHarryh** [comment]
> ```
> # *** ArkPets Log - desktop (PID30704) ***
> # Created: 2023-05-18 19:24:20,962
> # OS: Windows 11 (amd64)
> # Java version: 17.0.7
> # Working directory: D:\ArkPets
> 
> 19:24:21,906 [INFO] System: Entering the app of DesktopLauncher
> 19:24:26,333 [INFO] Launcher: Initializing (JavaFX 20-ea, ArkPets 2.1.0)
> 19:24:26,334 [DEBUG] Launcher: Property file.encoding = GBK
> 19:24:26,334 [DEBUG] Launcher: Property sun.jnu.encoding = GBK
> 19:24:26,334 [DEBUG] Launcher: Default charset = GBK
> 19:24:26,378 [INFO] Launcher: Initialized
> 19:24:28,605 [INFO] Network: Downloading https://arkpets.harryh.cn/p/arkpets/client/api.php?type=queryVersion&cliVer=2.1.0&source=auto to temp/ApiQueryVersionCache
> 19:24:29,096 [WARN] ModelManager: Failed to initialize model dataset due to file not found. (models_data.json (系统找不到指定的文件。))
> 19:24:29,098 [INFO] ModelManager: Search "" (0)
> 19:24:29,128 [INFO] ModelManager: Reloaded
> 19:24:31,095 [INFO] Network: Downloaded temp/ApiQueryVersionCache , file size: 183
> 19:24:31,096 [INFO] Checker: Application version check finished
> 19:24:46,155 [INFO] System: Exited from DesktopLauncher successfully
> ```

运行时日志中输出的字符集属性都是正常的（`GBK`），现在我们正在调查其他原因。

值得注意的是，在你的程序界面中，字符编码似乎被全部右移了 3 个字符。例如：
`A -> D` `r -> u` `k -> n`。

> Update:  
> 感觉类似于凯撒加密。请你回忆一下电脑有没有出现过奇怪的现象，安装过特别的软件，调整过特别的设置？

**Comment by isHarryh** [comment]
> 乱码问题罕见，之前遇到过一个用户也是乱码：
> 
> ![-221e85888b04a436.jpg](https://github.com/isHarryh/Ark-Pets/assets/107977864/a7fbeb11-aa4f-418d-8929-969e2f07b3f1)
> 
> 但他的乱码情况和你的不一样。

经过排查，这个用户是因为将系统字体 微软雅黑 的字体文件替换掉了导致的乱码问题。  
你是否也有过类似的设置修改？

**Comment by itscpj** [comment]
> > 乱码问题罕见，之前遇到过一个用户也是乱码：
> > ![-221e85888b04a436.jpg](https://user-images.githubusercontent.com/107977864/238174314-a7fbeb11-aa4f-418d-8929-969e2f07b3f1.jpg)
> > 但他的乱码情况和你的不一样。
> 
> 经过排查，这个用户是因为将系统字体 微软雅黑 的字体文件替换掉了导致的乱码问题。 你是否也有过类似的设置修改？

是的，替换成了新雅黑（Y轴抗锯齿版本）

**Comment by isHarryh** [comment]
现在已将OTF字体文件（思源黑体 Source Han Sans CN）内置到程序资源中，使其不再使用系统默认字体。

我已重新上传`v2.1.0-beta`的程序文件，请你重新安装，并验证是否解决。

**Comment by itscpj** [comment]
> 现在已将OTF字体文件（思源黑体 Source Han Sans CN）内置到程序资源中，使其不再使用系统默认字体。
> 
> 我已重新上传`v2.1.0-beta`的程序文件，请你重新安装，并验证是否解决。

问题已解决，界面不再乱码
