### ISSUE TITLE
[Question] 双屏/多屏 小人好像只能出现在主屏幕上

### ISSUE THREAD

**Issue by wickcy** [isHarryh/Ark-Pets#33]
日常是用双屏，小人只会出现在主屏幕上，也无法拖到到副屏上，软件里也没有找到怎么设置

**Comment by isHarryh** [comment]
请注意你使用的版本。多屏幕在`v2.1.0`后才开始支持。

**Comment by wickcy** [comment]
> 

好的感谢 更新v.2.1.0之后确实可以了，等待正式版本
