### ISSUE TITLE
[Bug] 多屏幕底边未对齐时小人移动问题

### ISSUE THREAD

**Issue by nebulas-star** [isHarryh/Ark-Pets#34]
版本：`v2.1.0-beta`
问题：双屏配置如图。
![image](https://github.com/isHarryh/Ark-Pets/assets/33574791/7278b522-dac8-4d73-bd8c-f95bf21158b4)
小人从2号屏幕底边向右行走会进入1号屏幕底边「下方」的无法显示亦无法将鼠标移入的位置。
建议避免该情况。

**Comment by nebulas-star** [comment]
另：当小人从2号屏幕顶部窗口向右移动时出现了「掉落」至1号屏幕「顶线」所在的平面的情况（「坐下」动作时只有脚部在屏幕内）
启用截图的情况下所有小人都会「掉落」至屏幕底面；此时1号屏幕内的小人都会「掉入」如主题所述的位置。

**Comment by isHarryh** [comment]
主题所述问题是由目前判定重力场边界的算法引起的：目前重力场边界的设定是 **恰能容纳所有屏幕的外接矩形**，这样设计沿用了前面版本的单屏幕的原有边界判定模式，也是为了简化程序开发。

后续可能对该问题提供修复优化。

**Comment by isHarryh** [comment]
~~已上传测试版本，尝试修复此问题，请你验证是否解决。~~

**Comment by isHarryh** [comment]
已于 1e231c9c8d140548256f5e10f54d0cd9d5f66d48 修复此问题，本人在多屏幕上测试证明已解决。此议题将关闭。
