### ISSUE TITLE
[Feature Request] 添加自定义桌宠窗口大小的功能

### ISSUE THREAD

**Issue by WSMTBG** [isHarryh/Ark-Pets#37]
感谢这款软件让我可以将员工放在桌面上。但是您能否添加一个设置，让用户手动调整桌面宠物窗口的大小并记住
尤其是在宽度方面，有些桌面宠物动画只有宽度的中点，占据了比较长的区域，比如凯尔奇皮肤

**Comment by isHarryh** [comment]
你的陈述似乎来自机器翻译，如果你不擅长中文，可以使用英语或其他语言提问。

这段话可能应该修改为：
> 感谢这款软件让我可以将干员放在桌面上。但是您能否添加一个设置，让用户手动调整桌宠窗口的大小并记忆。
> 尤其是在宽度方面，有些桌宠动画的宽度只有窗口宽度的一半，导致窗口占据了比较长的区域，比如凯尔希的皮肤。

窗口占据较大空白的原因，其实是因为目前我们的桌宠窗口是一个大小固定的矩形（ https://github.com/isHarryh/Ark-Pets/issues/4#issuecomment-1493255895 ），该矩形的尺寸主要取决于桌宠的动画可能伸展到的尺寸，来防止画面溢出。

后续可能会添加一个设置，用于控制 **防止画面溢出的强度** （仍然是自动设置尺寸而非手动调节），以增减空白区域的尺寸。

**Comment by isHarryh** [comment]
已于 6c4665b984aafae7240e1d219c0acd1d6ed26ee2 增加此功能。现在提供了“最宽”“较宽”“标准（默认）”“较窄”“最窄”五个窗口边界级别，用户可以在启动器“选项”页面自行调整。
