### ISSUE TITLE
[Enhancement] Windows安装程序细节调整

### ISSUE THREAD

**Issue by ZXAS007** [isHarryh/Ark-Pets#47]
**软件版本**：v2.2.1
默认安装目录是 C:\Program Files
安装时需要申请管理员权限（不然C盘拒绝访问）

**Comment by ZXAS007** [comment]
启动的时候也需要右键管理员权限运行否则无法更改设置（更改后不需要）

**Comment by isHarryh** [comment]
已于 7db99c32f44d86ff23b9857fec21e5e024f8a9b8 解决此问题，将在下个版本发布。

默认安装目录已变更为 C:\Users\用户文件夹\AppData\Local\Programs\ ，变更后通常不需要管理员权限来安装和启动。
