### ISSUE TITLE
[Bug] 动作保持时拖动浮起

### ISSUE THREAD

**Issue by dnyyfb** [isHarryh/Ark-Pets#48]
**软件版本**：v2.2.1
**运行环境**：Windows 11

#### 问题描述
任意桌宠进入动作保持模式后，在任务栏上以坐立姿势平移或竖向短距离拖动(竖向脱离任务栏后会站立，恢复正常)时会突然浮起然后恢复，看起来很怪

截图：  
<img width="239" alt="屏幕截图" src="https://github.com/isHarryh/Ark-Pets/assets/63101620/31c6d6e0-2ea7-42b8-a994-db0a7f566b7b"><br>

录屏：  
https://github.com/isHarryh/Ark-Pets/assets/63101620/8b86e366-9369-4f94-9462-9a2728a62028

#### 复现方法
在当前主机上稳定出现(记得以前是没有这种现象的)，其他的设备还没有测试

**Comment by isHarryh** [comment]
非常感谢你的反馈。该问题原因已被定位于：

https://github.com/isHarryh/Ark-Pets/blob/17d3fded56a6b92b4dabe62945897b8b7df1514b/core/src/cn/harryh/arkpets/ArkPets.java#L426-L430

其中 L427 `WD_postar.set($pos_x, $pos_y);` 中的 Y 参数也需要加上 OFFSET_Y 以进行同步。

此问题将在后续版本修复。

**Comment by isHarryh** [comment]
已于 [v2.3.0](https://github.com/isHarryh/Ark-Pets/releases/tag/v2.3.0) 修复此问题。
