### ISSUE TITLE
[Bug] 开机自启动后窗口在任务栏中保持高亮状态

### ISSUE THREAD

**Issue by LePereLee** [isHarryh/Ark-Pets#49]
**软件版本**：v2.0.1
**运行环境**：Windows 10

#### 问题描述
ArkPets core使用开机自启动后，软件窗口在任务栏中一直保持高亮状态，点击该窗口也无济于事

#### 复现方法
在程序设置中勾选开机自动启动桌宠，重启电脑，现在由于其会开机自启动，所以会自动弹出ArkPets的窗口在任务栏中，且其在任务栏中会处于高亮提示状态。在一般情况下，任务栏中窗口的高亮可以通过点击该窗口来解除，但是该问题无法由此解决，软件的窗口会一直在任务栏中高亮，除非关闭该程序。
![屏幕截图 2023-11-01 152814](https://github.com/isHarryh/Ark-Pets/assets/58317350/b7b2f8fc-c148-40ae-9751-32ed984107d2)

**Comment by isHarryh** [comment]
此问题归属于议题 #39 ，原因已查明，将在下个版本修复。
