### ISSUE TITLE
[Bug] 小人在空中被右键后漂浮不会落下

### ISSUE THREAD

**Issue by qaq163com** [isHarryh/Ark-Pets#5]

**Comment by isHarryh** [comment]
此问题确实存在，初步判定为`InputProcessor`中代码逻辑设置错误，将在后续修复。感谢您的关注。

**Comment by isHarryh** [comment]
已于[`9648fe`](https://github.com/isHarryh/Ark-Pets/commit/9648fe3089bb7b11b7693e2f61eed54a598b2023)修复此问题。
