### ISSUE TITLE
[Feature Request] 增加模型手动下载渠道等功能

### ISSUE THREAD

**Issue by iammmmmmm** [isHarryh/Ark-Pets#57]
**软件版本**：v2.4.0

#### 描述

1. 希望增加模型手动下载渠道，或者是显眼的提示（也可能就是我瞎）
2. 希望在下载模型时提供下载路线选择的选项，我下载时失败了三次才成功，同时我注意到每次下载的路线似乎不一样
谢谢！

**Comment by isHarryh** [comment]
> 
> **软件版本**：v2.4.0
> 
> #### 描述
> 
> 1. 希望增加模型手动下载渠道，或者是显眼的提示（也可能就是我瞎）
> 2. 希望在下载模型时提供下载路线选择的选项，我下载时失败了三次才成功，同时我注意到每次下载的路线似乎不一样
> 谢谢！
> 

1. 考虑加入此功能。目前确实暂未在 **软件内** 提供手动下载渠道，但是已经支持导入模型压缩包，可以手动前往 Ark-Models 仓库下载。
2. 不考虑此功能。目前下载路线按照 **连通性和TCP延迟** 进行优先级自动排序。同时，当某个下载路线出错时，会大幅降低其优先级，所以下次下载就会自动选择其他可能成功的路线。如果提供手动路线选择，那么用户需要自己清楚哪个路线可以用，所以与其让用户尝试各个路线后进行繁琐的判断，不如让程序进行自动试错，用户只需要执行简单的下载操作即可。综上所述，此功能可能是没有必要的。

**Comment by iammmmmmm** [comment]
对于2，是否可以添加一个提示，告诉用户多尝试几次就可以下载了，或者在程序内部自动多尝试几次。
另外half nothing fork了一个版本，在那个版本中托盘程序变得更好用了，您可以考虑合并吗？
感谢您的回复！

**Comment by half-nothing** [comment]
> 对于2，是否可以添加一个提示，告诉用户多尝试几次就可以下载了，或者在程序内部自动多尝试几次。 另外half nothing fork了一个版本，在那个版本中托盘程序变得更好用了，您可以考虑合并吗？ 感谢您的回复！

感谢你的喜欢
但如果你说的是现在我的fork的话，那么很遗憾告诉您这个fork目前并不能合并，因为托盘程序还没有完全修改完，它并不能与桌宠一起正常的工作

**Comment by iammmmmmm** [comment]
对于不能合并我表示遗憾，但ark pets依旧是款优秀的软件。
我还想问一下您几个其它的问题，如果不耽误您的时间的话。
1. 为什么不使用slf4j这种日志框架呢？
2. 不止日志，比如下载功能，高级的fx控件都有现成的依赖库比如httpclient ，rxcontroler 
3. 您在界面设计中是否使用了sencebuilder这个工具或者其它类似的工具，我尝试用工具打开您的fxml文件但显示并不正常，难以用工具修改界面
很抱歉继续打扰您！

**Comment by half-nothing** [comment]
虽然我不是项目的主要开发人员，但我可以说一下我的理解：
1、slf4j我看来只是一种接口，因为他不提供具体的实现（这里指的是输出日志的功能），项目中用的是log4j，这是一种slf4j实现（其实有点不恰当，但是意思到了就行）
2、你说的httpclient只是建立http连接，如果想要下载文件，还是要自己打开stream下载
3、没有，至少我看不出来生成的痕迹，根据git提交记录来看大部分都是手敲的

**Comment by isHarryh** [comment]
> 我还想问一下您几个其它的问题，如果不耽误您的时间的话。
> 1. 为什么不使用slf4j这种日志框架呢？
> 2. 不止日志，比如下载功能，高级的fx控件都有现成的依赖库比如httpclient ，rxcontroler 
> 3. 您在界面设计中是否使用了sencebuilder这个工具或者其它类似的工具，我尝试用工具打开您的fxml文件但显示并不正常，难以用工具修改界面

1. Half-nothing 已经解释清楚了。
2. 没有使用现成库是因为 ①简单下载任务的编写实现并不复杂 ②添加此类依赖库会增加项目复杂度和开发人员学习成本 ③添加此类依赖库有功能冗余。
3. 开发过程中我使用 SceneBuilder + 手动编写的方式来构建 FXML，以便于灵活地添加组件和即时观察视觉效果。提交前会进行代码格式化和冗余属性值删除，所以 Half-nothing 认为是手敲的。

**Comment by isHarryh** [comment]
你提到无法正常打开 FXML，暂不清楚原因，可详细描述？

**Comment by iammmmmmm** [comment]
![image](https://github.com/isHarryh/Ark-Pets/assets/73742531/b2874d7b-6f3b-42cb-9e1e-e9de573e8340)
就像这样，右侧部分无法正常预览。不过其它的正常

**Comment by isHarryh** [comment]
> ![image](https://github.com/isHarryh/Ark-Pets/assets/73742531/b2874d7b-6f3b-42cb-9e1e-e9de573e8340)
> 就像这样，右侧部分无法正常预览。不过其它的正常

此问题是由于第三级节点 Pane 的 Visible 属性被默认设置为 false 导致的。因为我们早期设计的时候，三个子页面是合并到一个文档的，所以需要隐藏一下避免重叠。但是最新的 3.x 版本分支已经对其进行了模块化拆分，没有这个遗留问题了。

**Comment by iammmmmmm** [comment]
好的，再次感谢您的回复。

**Comment by isHarryh** [comment]
已于 741cf005040bcdc128d2a50bae0f314b3a6a54ad 添加了手动下载渠道的跳转链接，如下所示：

![Preview](https://github.com/isHarryh/Ark-Pets/assets/107977864/e5071405-84fb-4719-b2c2-880b62743380)

跳转地址 https://arkpets.harryh.cn/p/arkpets/?from=client#/help
