### ISSUE TITLE
[Feature Request] 扩大图像缩放倍率的自定义范围

### ISSUE THREAD

**Issue by Entiesci** [isHarryh/Ark-Pets#62]
**软件版本**：v3.0.0

#### 描述
可否自定义图像缩放倍率（x2.0在这边（本人电脑）看起来还是好小qwq）

**Comment by isHarryh** [comment]
已于 0f48bc0b3c31720385d4d3b1d4b47db84a9661c2 扩增了图像缩放倍率。（2.5倍、3.0倍）
