### ISSUE TITLE
[Feature Request] 窗口模式/游戏模式/浏览器模式

### ISSUE THREAD

**Issue by boxifu** [isHarryh/Ark-Pets#68]
软件版本：v3.1.0

描述
如题

想搞直播桌宠，但是好像现在的格式没法用直播软件捕捉。不知道后续能不能出透明背景的窗口或者网页模式来捕捉（虽然好像违背了桌宠的定义:> )

**Comment by isHarryh** [comment]
现在桌宠窗口样式是“工具窗口（TOOLWINDOW）”，这类似于输入法托盘、加速球。使用此种窗口是为了消除任务栏常驻图标并可在多桌面显示。由于使用了此种窗口，OBS等软件无法将其作为窗口捕捉的目标，属于正常现象。

后续可能会加入选项，使得可以自定义是否作为工具窗口显示。

**Comment by isHarryh** [comment]
> 现在桌宠窗口样式是“工具窗口（TOOLWINDOW）”，这类似于输入法托盘、加速球。使用此种窗口是为了消除任务栏常驻图标并可在多桌面显示。由于使用了此种窗口，OBS等软件无法将其作为窗口捕捉的目标，属于正常现象。
> 
> 后续可能会加入选项，使得可以自定义是否作为工具窗口显示。

已于 1af28e6a637e33c4da5e9eac0d2677abe2d53ccc 加入“是否以工具窗口（后台程序）模式启动桌宠”的设置项。

**Comment by isHarryh** [comment]
此议题的主要诉求已得到解决，现关闭此议题。
