### ISSUE TITLE
[Feature Request] 增加调整桌宠透明度的功能

### ISSUE THREAD

**Issue by Zzzz2129** [isHarryh/Ark-Pets#71]
**软件版本**：v3.1.0

#### 描述
希望增加调整桌宠透明度功能（包括透明模式下）

**Comment by lixiang-24** [comment]
臣附议

**Comment by isHarryh** [comment]
已于 cdb6a6f5b86807ed6b68a22bcbc30972b7483fdb 新增此特性。功能预览：

![image](https://github.com/user-attachments/assets/f70fa9e4-780d-4408-9d6c-ce6b648fd468)

将在新版本中一同发布。
