### ISSUE TITLE
[Bug] 干员薇薇安娜等模型走路时腿部动画异常

### ISSUE THREAD

**Issue by HyzenthlayER** [isHarryh/Ark-Pets#81]
**软件版本**：v3.3.0
**运行环境**：Windows 11

#### 问题描述
干员薇薇安娜的小人走路时有条腿不动，有时两条腿都不动，精英怪vvan的小人表现正常

#### 复现方法
正常启动即可

**Comment by isHarryh** [comment]
问题已确认，初步判断为骨骼变换问题。 ~~后续将通过不同运行时和模型来源的交叉测试进行排查。~~

结合目前的社区调查情况，该问题发生在以下模型身上：

1. 薇薇安娜（我方）：腿部动画错误
2. 深靛：腿部动画错误
3. 安洁莉娜（珊瑚海岸）：组件扭曲
4. 水月（忒斯特收藏动态立绘）：组件扭曲
5. 泥岩（敌方）：透明度错误
6. 潘乔·萨拉斯：透明度错误
7. W（敌方）：透明度错误
8. 高普尼克：透明度错误

**Comment by isHarryh** [comment]
经 @litwak913 调查，发现在预处理（适应画布和快照渲染）阶段，每次更换动画片段后，并没有重置骨骼，从而导致特定模型发生异常。具体而言，这是因为 `AnimationState.clearTrack` 方法调用后，不会重置骨骼，而是保留骨骼的当前动作。
